lesson answer page
framgia/fph_fels_rails_gail pull request #10
Opened 2019-02-26 05:03 UTC by ducaoga

-"Let's Learn" button redirects to a form/ answer page for that category 
- answer page displays all words and choices
- form cannot be submitted unless all words have been answered (script in jquery)
- submission will redirect back to the list of categories ( will change in next module)
- radio button ui is in css and not utilizing bootstrap since it doesnt work.

2019-02-27 07:14 UTC, inahsanjuan requested changes

2019-02-27 07:14 UTC, inahsanjuan commented on app/controllers/categories/lessons_controller.rb
> +    @lesson.answers.build
@ducaoga Here, you can generate answer objects from `category words`

`@category.words.each { |word| @lesson.answers.build(word: word) }`

This will build multiple `answer` objects, depending on the `word objects` from category.

2019-02-27 07:14 UTC, inahsanjuan commented on app/views/categories/lessons/new.html.erb
> +        <%= form_for(@lesson, url: category_lessons_path(@category)) do |f| %>
@ducaoga You can use `form_for([@category, @lesson]) do |f|`
This will automatically generate necessary url

2019-02-27 07:14 UTC, inahsanjuan commented on app/views/categories/lessons/new.html.erb
> +        <% @category.words.each do |word| %>
@ducaoga If you have applied the comment here, no need to loop with `each`: https://github.com/framgia/fph_fels_rails_gail/pull/10/files#diff-e4f6fa354094f66a324de42883fbe0b7R6

You can replace this, and wrap everything with `fields_for` method
- This will loop all `answer objects`, related to the `@lesson` object

2019-02-27 07:14 UTC, inahsanjuan commented on app/views/categories/lessons/new.html.erb
> +                <%= f.hidden_field :user_id, value: current_user.id %>
@ducaoga You can acess `current_user` anywhere, and the category info in you url. So you can remove these two hidden fields.

- In your controller, you can remove these param items
- You have to use correct associations like this:
![image](https://user-images.githubusercontent.com/20507565/53471901-2962d780-3aa1-11e9-9192-b020f1c31f19.png)

2019-02-27 07:14 UTC, inahsanjuan commented on app/views/categories/lessons/new.html.erb
> +                    <h4 class="text-center"><%= word.content %></h4>
@ducaoga If you have followed all comments above.

From your fields_for, you can get `word` object.

Example: 
If you use `f.fields_for :answers do |p|`
`p` variable will be the `answer` object that has been generated in the controller. 

To get **word** obect : `p.object.word`

2019-02-27 07:14 UTC, inahsanjuan commented on app/views/categories/lessons/new.html.erb
> +                                            <%= p.radio_button :choice_id, choice.id, id: "#{choice.id}"%>
@ducaoga 
You can do generate form inputs like this:
- `p.hidden_field :word_id `
- `p.hidden_field :choice_id `

`word_id` and `choiced_id` values will be generate from the `p.object`, which is an **answer object**

2019-02-28 03:13 UTC, ducaoga commented on app/views/categories/lessons/new.html.erb
> +                                            <%= p.radio_button :choice_id, choice.id, id: "#{choice.id}"%>
I changed my input hidden_field for word_id but cant change for choice_id since it will make my buttons unclickable or would cause an error "wrong number of arguments (given 1, expected 2..3)"

2019-02-28 04:01 UTC, merged