crud word page
framgia/fph_fels_rails_gail pull request #8
Opened 2019-02-18 06:13 UTC by ducaoga

-can display, add ,edit and delete words and its choices
-has validations.
-delete also delete word also deletes its choices in the database

2019-02-18 09:27 UTC, inahsanjuan requested changes

2019-02-18 09:27 UTC, inahsanjuan commented on app/controllers/admin/words_controller.rb
> +
@ducaoga Remove extra line spaces

2019-02-18 09:27 UTC, inahsanjuan commented on app/controllers/admin/words_controller.rb
> +        @choices = @word.choices.all
@ducaoga No need to add `all` method

2019-02-18 09:27 UTC, inahsanjuan commented on app/models/word.rb
> +  validates_associated :choices
@ducaoga 
https://prnt.sc/mmjzlq I could select more than one choice

There will be cases that front end validation fails, so it is always important to add validation in back end.
Please add custom validation here : 
- Require admin to select only ONE choice

2019-02-18 09:27 UTC, inahsanjuan commented on app/views/admin/categories/index.html.erb
> +                                        <%= link_to "Add Word", admin_category_words_path(category), class: "btn btn-primary btn-sm" %>
@ducaoga I made a mistake in this button in the sample application, `Add word` button must redirect to `words#new` not in `words#index`

2019-02-18 09:27 UTC, inahsanjuan commented on app/views/admin/categories/index.html.erb
> +                                <td class="col-2"><%= category.title %></td>
@ducaoga Add link here to redirect to `words#index`

2019-02-18 09:27 UTC, inahsanjuan commented on app/views/admin/words/index.html.erb
> +                        <% answer = word.choices.where(correct:true) %>
@ducaoga
Instead of this statement, I want to suggest a more advanced approach:


1. **You can create a method in your `Word` model to fetch the correct answer of your word like this:**

```
def correct_answer
  choices.find_by(correct: true).try(:content)
end
```
* Using `find_by` will let us get only one object, as oppose to `where` which gives us an array
* The `try` method will check if `:content` method exists, if it does, it will fetch with `.content` ref: https://apidock.com/rails/v3.2.1/Object/try

2. **In line `21` below, you can access this method by `word.correct_answer`**

2019-02-18 09:27 UTC, inahsanjuan commented on app/views/admin/words/index.html.erb
> +                            <td class="col-5"><%= answer.empty? ? "No Answer" : answer[0].content %></td>
@ducaoga Following the comment I had above, you can have a statement like this:
`word.correct_answer || "No answer"`

2019-02-18 09:27 UTC, inahsanjuan commented on app/controllers/admin/words_controller.rb
> +        @words = @category.words.all
@ducaoga You can remove `all`

2019-02-18 09:27 UTC, inahsanjuan commented on app/views/admin/words/edit.html.erb
> +                                <%= f.hidden_field :category_id, value: "#{@word.category_id}" %>
@ducaoga In your `URL` you can already get `category_id`, so no need to pass in the form
![image](https://user-images.githubusercontent.com/20507565/52940524-c33fcb80-33a1-11e9-8839-3b8ed6026a2e.png)

2019-02-18 09:27 UTC, inahsanjuan commented on app/controllers/admin/words_controller.rb
> +        @word = Word.new(word_params)
@ducaoga
Use the association being set in your model `has_many :choices`
```
@category = Category.find(params[:category_id])
@word = @category.words.new(word_params)
```

Then in `word_params` method, you can remove `:category_id`

2019-02-19 04:30 UTC, ducaoga commented on app/models/word.rb
> +  validates_associated :choices
I made use of the one you taught me although you suggested to search other ways. I think Ill make use that oppurtunity on the next works.

2019-02-19 07:54 UTC, inahsanjuan requested changes

2019-02-19 07:54 UTC, inahsanjuan commented on app/models/word.rb
> +    if answer > 1
@ducaoga A more fitting condition would be `unless answer == 1`, so it could validate if user did not select a choice

2019-02-19 08:03 UTC, merged